# This is a basic workflow to help you get started with Actions

name: CI

env:
  # The name of the main module repository
  main_project_module: app

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'gradle'

       

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Generate gradle
        run: gradle wrapper --gradle-version 7.5

        # Run Build Project
      - name: Build gradle project
        run: ./gradlew assembleDebug

        # Upload Artifact Build
      # Noted For Output [main_project_module]/build/outputs/apk/debug/
      - name: Upload APK Debug test app
        uses: actions/upload-artifact@v3
        with:
          name: Test app
          path: ${{ env.main_project_module }}/build/outputs/apk/debug/

    
